apiVersion: apps/v1
kind: Deployment
metadata:
name: express
labels:
  app: express
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: hello
      tier: hello
  spec:
    containers:
    - name: hello
      image: finleyma/express:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 3000
        name: express

---
apiVersion: v1
kind: Service
metadata:
name: svc-express
labels:
  app: express
spec:
ports:
  - port: 3000
    targetPort: 3000
selector:
  app: hello
  tier: hello
type: LoadBalancer
